### ISSUE TITLE
[Feature Request] Process only audio

### ISSUE THREAD

**Issue by DrAg0n141** [Josh5/unmanic#26]
Hi,

it would be nice to copy only Audio, select what format prefeer and language and delete the other not used audio streams. And an disable button for the create of the Stereo Stream.

**Comment by Josh5** [comment]
I'm not sure I can add all these requested features. I can add the ability to only copy the audio stream and not re-encode. I can add the ability to set a target. The problem I see is that most of the time, every video is people's library will be slightly different. Some videos may have DD 5.1, others 7.1, others DTS and still others just a stereo aac or mp3. There is no point in re-encoding a 5.1 channel audio to 7.1. Switching between DTS and DD often produces lower quality. So the way I saw it was the only real desirable option was to ensure a stereo audio stream existed for players that do not support multi-channel. Furthermore, the "language" of an audio stream is 100% relying on the orignial encoder having specified it in the name of that stream. and even then, there is no real simple standard to go by. It could be "en", "english", "English" or even something like "English Director's commentary". It gets very difficult to set an automated configuration for this. Under these circumstances the task would be far better suited to something like Handbreak rather than Unmanic.

What I might look at doing here is adding the ability to re-encode the audio to a particular audio codec. Eg. DTS. And I will add the config option to disable the creation of the stereo stream. Beyond that I believe it may be better to use a more advanced tool such as Handbreak for getting more refined results.
