### ISSUE TITLE
all cores and threads 100% for one worker

### ISSUE THREAD

**Issue by letrain02** [Josh5/unmanic#42]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

all cpu's are 100% and i only have 1 worker going. its been 3 hours and at only encoded at 60%. i have dual xeon 4 core processors.

### Steps to Reproduce

1. start docker, run 1 worker

**Expected behavior:** to use some cpu power, but not all

**Actual behaviour:** everything 100% all the time while encoding

**Reproduces how often:** 100% of the time

###  Version - 0.0.1-beta4~d54ee24 

The version can be found at teh footer of the WebUI. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

### Installation Method Used

Manually installed and run or run through Docker? Docker

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

i am using unraid. when it pegged all of my cores and threads at 100% i used cpu penning and dropped it to less so i could still use my server. they have been sitting at 100% for over 4 hours and it hasn't finished encoding even 1 file. i've used hand brake before and it didn't seem to eat this much. i'm also using /tmp/ instead of cache...not sure if that makes a difference.

**Comment by Josh5** [comment]
I've run tests of raw FFMPEG command line conversions vs Unmanic. They are very much the same. I'm not sure at this point how you would have better performance out of handbreak.
That being said, I believe there is a way for us to limit the CPU usage on the FFMPEG task. For this I have opened a project to look into adding a config option to limit the FFMPEG process. But no promises at this stage.

**Comment by chadblose** [comment]
I started the container in unRAID with additional parameter --cpu-shares=2 rather than using pinning. This way it's maxing out the CPU while letting all other processes take priority. The webUI and other containers are all performing great when I'm using them. It's keeping it as a background process essentially consuming idle CPU time.

**Comment by jfroebe** [comment]
I think a feature enhancement to select the number of threads for ffmpeg (--threads #) in th web interface would be helpful here. Ffmpeg will use the same number of threads as cpus, cores as the system has.

**Comment by Josh5** [comment]
I'm closing this issue because it is either no longer relevant due to the ability to now specify -threads as a FFMPEG option, or it is not a problem any longer.

**Comment by Brainwasher06** [comment]
Hello, 

I got a similar issue on my unraid server.

Basicly, no matter the CPU settings i use for unmanic, as soon as i start unamic all my CPU cores will go crazy and stay between 95% and 100% even if unamic use about 10% of my CPU (based on the "Docker" tab in unraid)

My files are stored on a RAID 5 managed by mdadm on a Debian virtual machine and the all thing is shared by samba to unraid and my local network. 

For what i can tell using htop, when unamic is active i got some wierd result like the virtual machine (qemu) and ffmpeg are both using above 70% of the CUP each ! (so at least 140% of cup wich dont make much sense to me) 

Despite the over CPU situation, i mannaged to convert all my anime with almost no errors, but since i moved to my movie library,  my virtual machine crash every few hours if unmanic is running. 

I use plex as media server and i've never noticed anything like this while plex is transcoding files. Any idea why my CPU goes crazy with unmanic  ? 

Version - 0.0.9~f50e330
