### ISSUE TITLE
Framework Discussing and Implementation

### ISSUE THREAD

**Issue by Dr-Crow** [Josh5/unmanic#58]
### Description

I wanted to start a discussion about the framework you are using for this project. It looks like you are using Tornado. Was there a reason behind this choice or were you the most familiar with it?

I ask because I used Flask in the past and found it to be easy to work with. Not only that, but it is pretty popular in terms of frameworks that work with Python. 

I noticed on your test folder readme you had the idea of testing the web UI through a series of API calls. I think this is good idea. Ideally, for this project we should have a strong separation between the backend and frontend. 

On that note, I think we should really have some sort of CLI for the backend. This would allow users to be able to convert there libraries in the command line if they wanted too. But it also allows people to know convert a couple of files if they wanted too. 

As for the frontend, it should really just be a wrapper for this backend CLI. Plus some extra magic, to handle a database and other extras. 

I know Flask would easily allow you to accomplish this setup. I am not sure about Tornado as I know started looking into last night when I saw your project. 

### Additional Information

I appreciate what you have done so far, just wanted to start a discussion before development got going too far.

**Comment by Josh5** [comment]
This is the first time I have used Tornado. It is far from something that I am familiar with :). I chose it because I wanted a framework that didn't come with any other bloat. I've used Django and Flask in the past. For this project I wanted to keep the WebUI minimal. Tornado is only needed for driving the front-end. The application does not rely on it. Unmanic was originally written as a CL application taking some basic params and running logging everything to the terminal. It then grew to allow multiple workers and then also added a front-end to display what was happening in the background through the WebUI. Once the WebUI was implemented, there was no need for the CLI params. So they were basically phased out completely.
A CLI may help greatly in development and testing. But let's no reason to go ham I think. I don't want to make a CLI wrapper for FFMPEG. People can just you FFMPEG. Feel free to implement one if it helps you out or you think it will help other's out. You can also implement a setting to disable the application's Front-end if you like...
Finally, I don't think we need to implement too much of a separation between front-end and back-end.

I dont think it is worth using anything other than Tornado at this point. So far I have really liked how simple it is and I have not found anything that I cannot do with it for this project.

I'd be interested in seeing some details on what you had in mind for the CLI tho. The CLI can be run with Tornado disabled.

**Comment by Josh5** [comment]
No further discussion. Closing issue
