### ISSUE TITLE
Add a file rename option for converted files

### ISSUE THREAD

**Issue by itimpi** [Josh5/unmanic#9]
At the moment there is no visible indication that a file has been converted other than examining the associated codec information.

In most cases I am converting from h264 to h265 as this seems to give a significant reduction in file size with no loss of quality.   It would be useful if the term 'x264' or 'h264' in the filename could be altered after conversion to something like 'x265' or 'HEVC' (with the rest of the filename staying unchanged).   Perhaps this could be implemented by using a simple replace 'xxxx' by 'yyyy' type capability?

It might also be desirable to have an option to add a 'x265' or 'HEVC' string to the filename if there is nothing to replace?

**Comment by Josh5** [comment]
I have decided that this is out of the scope of what Unmanic is trying to achieve.
That being said, it is my intention to add the ability to execute post-processing scripts on completed video files. This will allow people to write bash/python/whatever scripts to carry out custom tasks such as what you describe here once a conversion task is complete.
That will be done against the already open issue #31. So please watch that one for progress.

**Comment by SalmonSays** [comment]
I understand that interpreting the existing string and modifying it conditionally is out of the scope of this project, but is there any chance you'd consider an option to append something to the end of the filename just so that Sonarr/Radarr/etc recognizes the file has changed? This would solve a lot of problems dealing with outside indexers/aggregators, as they could treat an appended title as a scene group and trigger rescan/rename automatically.
